[project]
name = 'Decentralized-Quality-Standards-Compliance-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.assessment-coordination]
path = 'contracts/assessment-coordination.clar'
clarity_version = 2
epoch = 2.5

[contracts.corrective-action]
path = 'contracts/corrective-action.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
